/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false shared/types/cloudflare-env.d.ts` (hash: 2b0f9e7fb7911e846b693ff13baf74bf)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	NUXT_YOUTUBE_API_KEY: string;
	NUXT_OPENROUTER_API_KEY: string;
	NUXT_SESSION_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NUXT_YOUTUBE_API_KEY" | "NUXT_OPENROUTER_API_KEY" | "NUXT_SESSION_PASSWORD">> {}
}
